### PR TITLE
Hristo/deploy on gcp gke

### PR DESCRIPTION
**Pull request by hgueorguiev**
In this PR:
- Scripts and config templates to deploy backend portion (searxng, backend services) of Perplexity to `GCP Kubernetes Engine`
- Functionality to protect endpoints and Websocket with a token
- Scripts and config template to build and run frontend locally connected to remote backend
- Functionality to store secrets in `.env` files (best practices to prevent accidentally leanking secrets)
- Add VertexAI gemini models as Perplexity LLM providers

Small fixes:
- Docker compose restart errored containers, since node terminates process on unhandled errors
- Agent prompts were duplicating initial user query in prompt, this is not an issue for OpenAI models but appears Gemini model endpoints are upset when `user` and `model` utterances are not alternated and the redundant query
   user query causes the requests to error. 
   - All modified prompts were tested with OpenAI GPT and VertexAI Gemini models and appear to work correctly for both now

### CODE REVIEW

**Comment by hgueorguiev** [comment]
@ItzCrazyKns we wanted this deployed on K8s + VertexAI LLMs to experiment with and figured it would be good to contribute those changes back. Let me know what you think, thank you!

**Comment by ItzCrazyKns** [comment]
Hi, thanks for the PR! I think instead of merging this on the main branch we can create a separate branch for this only for those who want to deploy this on GCP so it doesn't cause any issues for normal users.

**Comment by ItzCrazyKns** [comment]
I've created a branch for this, can you re-open the PR for this branch so I can merge it.

https://github.com/ItzCrazyKns/Perplexica/tree/GCP

**Comment by hgueorguiev** [comment]
> I've created a branch for this, can you re-open the PR for this branch so I can merge it.
> 
> https://github.com/ItzCrazyKns/Perplexica/tree/GCP

Yes absolutely, will do tomorrow morns. also just fyi all the changes were done in a way where this does not affect the local/ existing functionality at all and just adds support to allow deploying on gcp as an option, make files allow spinning up both modalities and the config is backwards compatible (barring some cases my testing might have missed lol).

**Comment by ItzCrazyKns** [comment]
> > I've created a branch for this, can you re-open the PR for this branch so I can merge it.
> > https://github.com/ItzCrazyKns/Perplexica/tree/GCP
> 
> Yes absolutely, will do tomorrow. Also just fyi all the changes were done in a way where this does not affect the local/ existing functionality at all and just adds support to allow deploying on gcp as an option, make files allow spinning up both modalities and the config is backwards compatible (barring some cases my testing might have missed lol).

I need to take precautions for some cases, once we're done with most of the features I'll merge it into the main branch after testing. For now we can merge this into the branch I made.

**Comment by hgueorguiev** [comment]
> > > I've created a branch for this, can you re-open the PR for this branch so I can merge it.
> > > https://github.com/ItzCrazyKns/Perplexica/tree/GCP
> > 
> > 
> > Yes absolutely, will do tomorrow. Also just fyi all the changes were done in a way where this does not affect the local/ existing functionality at all and just adds support to allow deploying on gcp as an option, make files allow spinning up both modalities and the config is backwards compatible (barring some cases my testing might have missed lol).
> 
> I need to take precautions for some cases, once we're done with most of the features I'll merge it into the main branch after testing. For now we can merge this into the branch I made.

Sry for the delay, found a few more changes that needed to be added for gcp and also added Vertexai embeddings as an option ... will have a new PR going to the GCP branch shortly.

**Pull request closed without merging**
