### PR TITLE
🎉 New discover functionality

### PR DESCRIPTION
**Pull request by asifrahaman13**
The is a feature integration for the discover option.

Currently it only searches for some latest coole blogs on AI and technology.

SS 1: 
Screenshot from 2024-06-25 20-19-24

SS 2:
Screenshot from 2024-06-25 20-21-35

Currenlty the updates takes place every 60 seconds. Will also add more configurations to them. 

Uses mongodb services to store the data. Only 10 discover result is supported till now. Some parts are dummy like veiws etc.

I will keep adding new features to make it better.

### CODE REVIEW

**Comment by ItzCrazyKns** [comment]
Hi, thanks for the PR! I cannot merge this as I've already started working upon this. The database integration I've done is very different and the UI is coded on the basis of our Figma design. Sorry about this

**Comment by christomitov** [comment]
@ItzCrazyKns do you have a PR for it? I don't see it

**Comment by datascience279** [comment]
@ItzCrazyKns when we can expect this feature?

**Comment by terrabys** [comment]
@ItzCrazyKns any updates?

**Pull request closed without merging**
