### PR TITLE
Added automatic docker build on merge to master

### PR DESCRIPTION
**Pull request by andypenno**
Hey, loving the project! 

I tried to get this working on podman, but some issues with second order dependencies were causing the build to fail. After a couple of days of playing whack-a-mole I figured it would make more sense to add support for building using a GitHub actions workflow. I noticed issues with a similar PR due to the frontend needing a way to provide the backend API url to the client, so I've created a simple helper lib function within the frontend to provide the necessary definitions.

There's container images available to test on [my dockerhub profile](https://hub.docker.com/u/andypenno), although I've ensured all changes won't affect the local build process if people prefer to use that method instead.

Let me know what you think, I'm happy to make further changes if there's any concerns!

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

This PR includes:
- Automatic build & push to docker hub when pushing to master, or when triggering a workflow dispatch on master
- Automatic docker build on pull requests to validate changes
- Updated the docker-compose.yaml to use the container images, rather than building locally
- Added support for defining backend settings using the container environment  
  -> All options defined in config.toml can now be loaded instead from the environment 
  -> Order of precedence is environment definition, config.toml, and finally default inline configuration defined in config.ts
- Added support for defining frontend settings using the container environment 
  -> Added a library function to fetch the server environment definitions
  -> Modified existing calls to `process.env` to use the new library function 
  -> Left the initial statically compiled environment definitions in place as a backup definition, if no environment definitions are provided

Remaining tasks to complete before able to merge to [ItzCrazyKns/Perplexica](https://github.com/ItzCrazyKns/Perplexica):
- Add secret definitions for `DOCKER_USERNAME` and `DOCKER_PASSWORD` to [ItzCrazyKns/Perplexica](https://github.com/ItzCrazyKns/Perplexica) to ensure push to dockerhub works on base branch

### CODE REVIEW

**Comment by ItzCrazyKns** [comment]
There isn't a need for the environment variable route since the getServerEnv function can be marked as a server function (by putting "'use server'" on top of the lib file) and the environment variables will be exposed to it by default.

**Comment by andypenno** [comment]
Good to know, I'm still getting used to NextJS. Latest commit refactors to remove the API route, and use server-side rendering on the `getServerEnv` library function. I've used a switch statement to maintain the fallback to the statically compiled environment definitions provided in the container build. I've also included some minor updates to the documentation:
- Updated `README.md` to list the environment variables that have been added
- Updated `NETWORKING.md` to reflect the changes I've made to the `docker-compose.yaml`

**Comment by ItzCrazyKns** [comment]
And the rest of the changes LGTM

**Comment by andypenno** [comment]
What will you be using for the value of DOCKER_USERNAME? I'm assuming 'itzcrazykns', but just want to confirm.

**Comment by ItzCrazyKns** [comment]
> What will you be using for the value of DOCKER_USERNAME? I'm assuming 'itzcrazykns', but just want to confirm.

Its `itzcrazykns1337`, I will first push the images to hub before merging this PR

**Comment by andypenno** [comment]
Nice one, I've updated the appropriate references. Once you've added the secrets we should be good to go :+1:

**Comment by ItzCrazyKns** [comment]
The changes to the reviews are still pending.

**Comment by andypenno** [comment]
I'm not seeing any reviews on my end, was there another change that was requested that I'm not seeing?

**Pull request closed without merging**
