### PR TITLE
chore: change searxng service export port

### PR DESCRIPTION
**Pull request by aiyogg**
expose defines the (incoming) port or a range of ports that Compose exposes from the container. 

[expose](https://docs.docker.com/compose/compose-file/05-services/#expose)

### CODE REVIEW

**Comment by ItzCrazyKns** [comment]
It forwards the port 8080 to 4000. Additionally we make contact over the Perplexica network so there isn't a need for this.

**Comment by aiyogg** [comment]
> It forwards the port 8080 to 4000. Additionally we make contact over the Perplexica network so there isn't a need for this.

After reading the Docker Compose documentation, I believe that the export field indicates that this port can be accessed by other internal services within the same compose. I’m interested to know your understanding of it as well.

**Comment by ItzCrazyKns** [comment]
I read the documentation again and here's what I come up with: In the current setup the `ports` directive maps `8080` to `4000` which allows containers to communicate within the Docker network and also provides external access. The `expose` keyword can be unnecessary since `expose` only signals which ports containers should listen on without mapping them externally a function already covered by `ports` in our configuration so I'll remove it. Still there won't be any need since its covered by the `ports` field

**Comment by aiyogg** [comment]
You got it! It's good to remove it.

**Pull request closed without merging**
