### PR TITLE
Integrate Gemini 1.0 Pro Chat Model and Google Embedding -001 Model for Enhanced Perplexica Capabilities

### PR DESCRIPTION
**Pull request by Nipurn123**
This pull request that I have created  introduces the integration of the **Gemini 1.0 Pro Chat Model** and the **Google Embedding -001 Model** into our Perplexica application . The following changes have been made to enhance our capabilities in generative AI and embeddings.

### Key Changes
- **New Models Added**:
  - Integrated Gemini 1.0 Pro Chat Model for enhanced conversational capabilities.
  - Integrated Google Embedding -001 Model for improved text embeddings.

- **File Modifications**:
  - **`src/config.ts`**: 
    - Added configuration settings for the Gemini API key.
  - **`src/lib/providers/gemini.ts`**:
    - Implemented functions to load the Gemini chat and embedding models.
    - Error handling added for model loading failures.
  - **`src/lib/providers/index.ts`**:
    - Updated the chat model and embedding model providers to include Gemini.
  - **`src/routes/config.ts`**:
    - Updated routes to handle Gemini API key retrieval.
  - **`ui/components/SettingsDialog.tsx`**:
    - Added input field for users to enter their Gemini API key in the settings dialog.

### CODE REVIEW

**Comment by Nipurn123** [comment]
Hi, I realised that I forgot to include the dependency @langchain/google-genai, so I've created this new pull request to address that. Additionally, since this is my first genuine PR, I would greatly appreciate it if you could take the time to review all the commits thoroughly. Thank you!

**Comment by Nipurn123** [comment]
I've made this change to the `package.json` within the same PR. I apologize for the cumbersome process I chose earlier to update in PR #285.

**Comment by ItzCrazyKns** [comment]
Hi, the changes LGTM. But you've added the next dependency in the package file of the backend.

**Comment by Nipurn123** [comment]
Hey I have removed that next dependency which by the way I am not sure why I have added before , but I have removed it from the backend package.json file

**Comment by ItzCrazyKns** [comment]
Hi, thanks. I will merge it after the testing

**Pull request closed without merging**
