### PR TITLE
Hristo/gcp deploy vertexai models embeddings

### PR DESCRIPTION
**Pull request by hgueorguiev**
In this PR:

- Scripts and config templates to deploy backend portion (searxng, backend services) of Perplexity to GCP Kubernetes Engine
- Functionality to protect endpoints and Websocket with a token
- Scripts and config template to build and run frontend locally connected to remote backend
- Functionality to store secrets in .env files (best practices to prevent accidentally leanking secrets)
- Add VertexAI gemini models as Perplexity LLM providers
- Add VertexAI text embeddings as Perplexity LLM providers

Small fixes:

- Docker compose restart errored containers, since node terminates process on unhandled errors
- Agent prompts were duplicating initial user query in prompt, this is not an issue for OpenAI models but appears Gemini model endpoints are upset when user and model utterances are not alternated and the redundant query user query causes the requests to error.
- All modified prompts were tested with OpenAI GPT and VertexAI Gemini models and appear to work correctly for both now

### CODE REVIEW

**Comment by hgueorguiev** [comment]
@ItzCrazyKns here are the GCP and VertexAi provider changes, as we discussed. Again sry for the delay.

**Comment by ItzCrazyKns** [comment]
> @ItzCrazyKns here are the GCP and VertexAi provider changes, as we discussed. Again sry for the delay.

Hi, no worries. Just before I merge, have you tested these out and do they work? I won't be able to test it from my side.

**Comment by hgueorguiev** [comment]
> > @ItzCrazyKns here are the GCP and VertexAi provider changes, as we discussed. Again sry for the delay.
> 
> Hi, no worries. Just before I merge, have you tested these out and do they work? I won't be able to test it from my side.

Yes. We have an instance up on GCP that is actively using both the Vertex embeddings and both Gemini 1.0 and 1.5.

**Comment by ItzCrazyKns** [comment]
Alright, thank you so much.

**Pull request merged**
