### PR TITLE
Adapt light mode

### PR DESCRIPTION
**Pull request by WanQuanXie**
see #125

### CODE REVIEW

**Comment by ItzCrazyKns** [comment]
Thanks for the PR! I'll review it before merging it so we don't face any issues

**Comment by WanQuanXie** [comment]
Just a simple implement, and maybe the some theme styles are not so pretty, welcome advice❤️

**Comment by ItzCrazyKns** [comment]
Do you have a discord account so we can communicate better? You can message me at `itzcrazykns`

**Comment by ItzCrazyKns** [comment]
The changes look good but the dark theme doesn't seems to be perfectly aligned with the current dark theme. Its a little different, can you take a look at it

**Comment by WanQuanXie** [comment]
@ItzCrazyKns Yes, and I have already joined our channel. But I'm not skillful to use discord, can you message me at `E|vi5` and let me find you.

**Comment by WanQuanXie** [comment]
> The changes look good but the dark theme doesn't seems to be perfectly aligned with the current dark theme. Its a little different, can you take a look at it

More details?

**Comment by WanQuanXie** [comment]
@ItzCrazyKns I realigned the dark theme, check again?

**Comment by ItzCrazyKns** [comment]
Just checked it out, there are a lot of issues. The hover for most of the things (like the focus modes, etc.) doesn't work. I think we need to change the colors of the light theme a little bit.

**Comment by WanQuanXie** [comment]
Thanks advices. I'll test it more detail.

**Review by WanQuanXie — COMMENTED** [review]
I'm not recommend to use pure arrow function for the React Component. That will lead the component be rendered to a anonymous component and hard to find and debug with the ReactDevTool in Browser. Arrow function component should work pair with `displayName` attribute which looks like this: `Input.displayName = 'Input'`, or directly use `function`

**Comment by ItzCrazyKns** [comment]
> I'm not recommend to use pure arrow function for the React Component. That will lead the component be rendered to an anonymous component and hard to find and debug with the ReactDevTool in Browser. Arrow function component should work pair with `displayName` attribute which looks like this: `Input.displayName = 'Input'`, or directly use `function`

Just exported them as default and added name so they should no longer be anonymous and show up on RDT.

**Comment by ItzCrazyKns** [comment]
Thanks @WanQuanXie!

**Comment by WanQuanXie** [comment]
Happy to help🚀

**Pull request merged**
